#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

modelVersion: '3.0'
dependencies:
- ID: github.com/SeldonIO/MLServer+1.5.0
  additional_info:
    fossa-attribution:
      Description: An inference server for your machine learning models, including support for multiple frameworks, multi-model serving and more
      Package: https://github.com/SeldonIO/MLServer
      Source: git
      Version: 1.5.0
      Hash: f9db7ab85ef557c2329a66e8858206817c8cce32
      licenses:
      - Apache-2.0
      Title: mlserver
      DownloadURL: https://github.com/SeldonIO/MLServer/archive/1.5.0.tar.gz
  bazaar:
    register: 'no'
    prim: 2/CTX1039304
    community_link: https://github.com/SeldonIO/MLServer
    community_name: SeldonIO
    community_url: https://github.com/SeldonIO/MLServer
    component_comment: ''
    component_highlevel_description: 
    component_name: MLServer
    component_platform: linux
    component_programing_language: Python
    component_version: 1.5.0
    licenses:
    - FAL1159004/20 (Apache License 2.0 (Apache-2.0))
    src_download_link: https://github.com/SeldonIO/MLServer/archive/1.5.0.tar.gz
    stako_decision_reason: automatic
    stako: ESW2
    stako_comment: ''
    bazaarurl: https://scas.internal.ericsson.com/search3pp?id=1085547&id-filter=equals&rowDisplay=Card-Simple
    recode: ''
    retext: ''
    country: United States
    crypto: No Encryption
  encryptions:
    used:
    - ''
  evms:
    register: 'yes'
    product_name: github.com/SeldonIO/MLServer
    target_sw: linux
    vendor: git
    version: v1.5.0
    web_url: https://github.com/SeldonIO/MLServer
  licenses:
  - Apache-2.0
  name: mlserver
  primary:
  - this
  subcomponent: false
  type: FOSS
  versions:
  - 1.5.0
  - f9db7ab85ef557c2329a66e8858206817c8cce32
  mimer:
    linking: Static
    product_number: CTX1039304
    product_version_label: 1.5.0
    obligation: Including the full license text in a prominent place with the software
      when the FOSS is distributed
    usage: Use as is
    primary: 'True'